# Generated by Django 4.2.4 on 2023-08-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_veiculo_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='km',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='placa',
        ),
    ]
